default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: search_trends_rails_development

test:
  <<: *default
  database: search_trends_rails_test

production:
  <<: *default
  database: search_trends_rails_production
  username: search_trends_rails
  password: <%= ENV["SEARCH_TRENDS_RAILS_DATABASE_PASSWORD"] %>
